//! Captured scientific input definition referenced by the workload-v3 root.
//! No state is regenerated by this descriptor, and no data format is inferred
//! from a kernel name, installed default or host-owned integration formula.
use super::{BulkRecord, INSTANCE_SCHEMA, InputIdentity, ObjectState};
use crate::{
    Error, ErrorCode, ExecutionProfile, FiniteF64, Limits, codec,
    projection::{Project, object},
};
use orishu_resource::ApiVersion;
use orishu_workload::{ComponentInstanceId, canonical::CanonicalValue as V};
use serde::{Deserialize, Serialize};

/// Portable captured scientific execution definition, one descriptor per workload.
pub const EXECUTION_SCHEMA: &str = "orishu.simulation.execution/v1";
/// Scene-bearing execution descriptor; v1 numeric-only bytes remain unchanged.
pub const EXECUTION_SCENE_SCHEMA: &str = "orishu.simulation.execution/v2";
/// Bounded metadata, separate from potentially large scientific state blobs.
pub const MAX_EXECUTION_BYTES: usize = 1024 * 1024;

/// One kernel's captured setup context and portable initial state/history.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CapturedKernel {
    /// Exact selected workload graph instance.
    pub instance: ComponentInstanceId,
    /// Canonical `InstanceContext` input. Configuration/domain references are
    /// carried inside it; all those bytes must be in the workload closure too.
    pub context: InputIdentity,
    /// Captured portable field state or integrator history. Never a request to
    /// initialize at worker admission, even for the initial run boundary.
    pub state: InputIdentity,
}
/// One independently advancing field and its captured coupling projection.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CapturedField {
    /// Selected executable use and initial field state.
    pub kernel: CapturedKernel,
    /// Exact standard coupled-entity packet; kinematics must agree with objects.
    pub coupled: InputIdentity,
}
/// Initial scientific boundary of the fixed field-force/integration profile.
/// This is an immutable workload artifact, not the editable experiment document
/// or a checkpoint/run descriptor. V2 carries shared scene composition; emitter
/// blueprints still need explicit profile integration, not silent dropping.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ExecutionDefinition {
    /// [`EXECUTION_SCHEMA`] without scene, or [`EXECUTION_SCENE_SCHEMA`] with one.
    pub api_version: ApiVersion,
    /// One field-force evaluation followed by one selected integration stage.
    pub profile: ExecutionProfile,
    /// Authored fixed step in seconds, never a wall-clock/render increment.
    pub timestep_seconds: FiniteF64,
    /// Whole intrinsic/Dynamics numeric object state, including static objects.
    pub objects: InputIdentity,
    /// Complete initial composition and bounded authoring evidence. Mandatory
    /// for v2; forbidden for v1. Not a serialized Kagami document or a catalog.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scene: Option<InputIdentity>,
    /// Complete field set in strictly ascending kernel instance ID order.
    pub fields: Vec<CapturedField>,
    /// Exactly one selected dynamics integrator, including for empty membership.
    pub dynamics: CapturedKernel,
}
fn limits(fields: usize) -> Limits {
    Limits {
        max_payload_bytes: MAX_EXECUTION_BYTES,
        max_values: 65_536,
        max_depth: 12,
        max_text_bytes: 256,
        max_schema_items: fields,
        ..Limits::default()
    }
}
impl ExecutionDefinition {
    /// Bound the raw descriptor and check intrinsic references/roles/order.
    /// Selected-context agreement, blob integrity, dimensions and numerical state
    /// validity remain independent profile/runtime admission obligations.
    pub fn validate(&self, max_fields: usize) -> Result<(), Error> {
        if !matches!(
            (self.api_version.as_str(), self.scene.as_ref()),
            (EXECUTION_SCHEMA, None) | (EXECUTION_SCENE_SCHEMA, Some(_))
        ) {
            return Err(Error::new(
                ErrorCode::UnsupportedVersion,
                "apiVersion",
                "unsupported execution definition",
            ));
        }
        if self
            .scene
            .as_ref()
            .is_some_and(|s| s.schema.as_str() != super::SCENE_SCHEMA || s.value_count != 1)
        {
            return Err(Error::malformed("scene", "invalid scene descriptor"));
        }
        if self.fields.len() > max_fields {
            return Err(Error::new(
                ErrorCode::LimitExceeded,
                "fields",
                "field count exceeded",
            ));
        }
        if !self.timestep_seconds.is_positive()
            || self.objects.schema.as_str() != ObjectState::SCHEMA
            || self
                .fields
                .windows(2)
                .any(|f| f[0].kernel.instance >= f[1].kernel.instance)
            || self
                .fields
                .iter()
                .any(|f| f.kernel.instance == self.dynamics.instance)
        {
            return Err(Error::malformed(
                "execution",
                "invalid timestep, objects or instance order",
            ));
        }
        for kernel in self
            .fields
            .iter()
            .map(|f| &f.kernel)
            .chain([&self.dynamics])
        {
            if kernel.context.schema.as_str() != INSTANCE_SCHEMA
                || kernel.context.value_count != 1
                || kernel.context.byte_length > super::MAX_CONTEXT_BYTES as u64
            {
                return Err(Error::malformed(
                    "context",
                    "invalid captured context descriptor",
                ));
            }
        }
        for field in &self.fields {
            if field.coupled.schema.as_str() != super::CoupledEntity::SCHEMA {
                return Err(Error::malformed("coupled", "invalid coupled-entity schema"));
            }
        }
        Ok(())
    }
    /// Explicit deterministic projection, preserving field order and all identities.
    pub fn to_cbor(&self, max_fields: usize) -> Result<Vec<u8>, Error> {
        self.validate(max_fields)?;
        codec::encode(&self.project(), &limits(max_fields), MAX_EXECUTION_BYTES)
    }
    /// Byte/tree-bounded canonical reader; no filesystem or artifact fetching.
    pub fn from_cbor(bytes: &[u8], max_fields: usize) -> Result<Self, Error> {
        let value: Self =
            codec::structured_from_cbor(bytes, &limits(max_fields), MAX_EXECUTION_BYTES)?;
        if value.to_cbor(max_fields)? != bytes {
            return Err(Error::malformed(
                "execution",
                "noncanonical execution definition",
            ));
        }
        Ok(value)
    }
}
impl Project for CapturedKernel {
    fn project(&self) -> V {
        object(vec![
            ("instance", Some(V::text(self.instance.as_str()))),
            ("context", Some(self.context.project())),
            ("state", Some(self.state.project())),
        ])
    }
}
impl Project for CapturedField {
    fn project(&self) -> V {
        object(vec![
            ("kernel", Some(self.kernel.project())),
            ("coupled", Some(self.coupled.project())),
        ])
    }
}
impl Project for ExecutionDefinition {
    fn project(&self) -> V {
        object(vec![
            ("apiVersion", Some(V::text(self.api_version.as_str()))),
            ("profile", Some(self.profile.project())),
            ("timestepSeconds", Some(self.timestep_seconds.project())),
            ("objects", Some(self.objects.project())),
            ("scene", self.scene.as_ref().map(Project::project)),
            ("fields", Some(self.fields.project())),
            ("dynamics", Some(self.dynamics.project())),
        ])
    }
}
