[package]
name = "orishu"
version = "0.1.1"
edition = "2024"
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Shared models and client interfaces for the Orishu simulation runtime"

[dependencies]
anyhow = "1.0.104"
async-trait = "0.1.89"
chrono = { version = "0.4", features = ["serde"] }
ciborium = "0.2.2"
http = "1.4.0"
orishu-identity = { workspace = true }
orishu-resource = { workspace = true }
reqwest = { version = "0.13.2", features = ["stream"] }
reqwest-middleware = { version = "0.5.1", features = ["http2", "rustls"] }
reqwest-netrc = "0.1.3"
rust-netrc = "0.1.2"
semver = "1.0.27"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
tokio = { version = "1", features = ["io-util", "fs"] }
futures-util = "0.3"
uom = { version = "0.38", features = ["autoconvert", "serde", "si"] }
serde-validate = "0.2"

[features]
# Define a simple feature named "my-rustls"
rustls = []
native-tls = []

# Optional: define a "default" feature set that is enabled automatically
default = ["rustls"]

[dev-dependencies]
tokio = "1.50"
wiremock = "0.6"
pretty_assertions = "1.0"
