//! Orishu's specialisation of the shared resource envelope.
//!
//! The structural shape — `apiVersion`, `kind`, `metadata`, `spec`, optional
//! `status` — lives in [`orishu_resource`], which Kagami's object-template
//! catalog shares. What stays here is what is Orishu's: the `orishu.dev/v1`
//! version, the [`ObjectMeta`] schema, and the [`ParseError`] a codec and a
//! workload-domain validation can produce.
//!
//! [`Name`] and [`ResourceUid`] are Orishu's descriptive resource label and its
//! system-assigned identifier. They are deliberately *not* a universal
//! identity: [`orishu_identity::FormationId`], [`orishu_identity::NodeId`],
//! and whatever canonical workload identity is chosen remain separate types
//! with their own authority and scope, and a value of one is never silently
//! reinterpreted as another.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// The shared structural envelope, specialised to Orishu metadata below.
///
/// Re-exported so that a consumer migrating from the previous
/// `orishu::model::manifest` definitions has one import to change rather than
/// several.
pub use orishu_resource::{
    AllowUnknown, ApiVersion, DenyUnknown, Kind, NoStatus, Resource, ResourceError, ResourceHeader,
    UnexpectedDiscriminator,
};

/// The only resource format version Orishu currently reads or writes.
pub const MANIFEST_API_VERSION: &str = "orishu.dev/v1";

/// [`MANIFEST_API_VERSION`] as the validated type the envelope carries.
///
/// # Panics
///
/// Never: the constant is checked by a unit test in this module.
pub fn api_version() -> ApiVersion {
    ApiVersion::from_static(MANIFEST_API_VERSION)
}

/// Manifested resource name.
///
/// A reusable human-readable label, not identity. Uniqueness, where it applies
/// at all, depends on the resource kind.
///
/// See <https://kubernetes.io/docs/concepts/overview/working-with-objects/names/>.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Name(pub String);

impl std::fmt::Display for Name {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

impl std::str::FromStr for Name {
    type Err = std::convert::Infallible;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(Name(s.to_string()))
    }
}

/// The unique identifier a system assigns to a manifested resource.
///
/// Unlike [`Name`], it is generated by the system that owns the resource rather
/// than chosen by an operator, and is unique within that resource's scope.
///
/// It is a *slot*, not an authority. Which identity fills it is the resource
/// kind's decision — a node resource carries its formation-assigned
/// [`orishu_identity::NodeId`] here — and projecting an identity into this slot
/// is one-way: membership, formation, and provenance decisions read the
/// identity type they own, never a `ResourceUid` reinterpreted as one.
///
/// See <https://kubernetes.io/docs/concepts/overview/working-with-objects/names/>.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ResourceUid(pub String);

impl std::fmt::Display for ResourceUid {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

impl std::str::FromStr for ResourceUid {
    type Err = std::convert::Infallible;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(ResourceUid(s.to_string()))
    }
}

/// Descriptive metadata for identifying and organizing Orishu resources.
///
/// Orishu's own metadata schema, not a universal one: Kagami's catalog
/// metadata names a catalog and a template instead, and neither is a
/// generalisation of the other.
///
/// Labels are descriptive. They are not membership identity, they do not
/// participate in formation identity, and they are not part of a workload
/// digest.
///
/// Based on Kubernetes ObjectMeta:
/// <https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/>.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ObjectMeta {
    /// Human-readable name of the resource.
    pub name: Name,

    /// System-assigned unique identifier, serialized as `uid`.
    ///
    /// Absent until the owning system has assigned one, which is why a
    /// client-authored document never carries it. What fills it is the resource
    /// kind's decision: a node resource carries its formation-assigned node ID,
    /// while [`name`](Self::name) stays a reusable human label.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uid: Option<ResourceUid>,

    /// Namespace defines the space within which each name must be unique.
    /// An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation.
    /// Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,

    /// Free-form key-value labels for filtering and grouping.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub labels: HashMap<String, String>,
}

impl ObjectMeta {
    /// Metadata carrying only a human-readable name.
    pub fn new(name: &str) -> Self {
        Self {
            name: Name(name.to_owned()),
            uid: None,
            namespace: None,
            labels: HashMap::default(),
        }
    }

    /// Metadata for a resource its owning system has already identified.
    ///
    /// The caller supplies the projection, because only the resource kind knows
    /// which of its identities belongs in [`uid`](Self::uid).
    pub fn identified(name: &str, uid: ResourceUid) -> Self {
        Self {
            uid: Some(uid),
            ..Self::new(name)
        }
    }
}

/// An Orishu resource: the shared envelope over [`ObjectMeta`].
///
/// A type alias, not a new definition — the structural type is
/// [`orishu_resource::Resource`], which `kagami-catalog` also uses. Each
/// resource module supplies its own `kind` and its own constructor, so a
/// resource cannot be built without naming what it is.
pub type Manifest<T, S> = Resource<ObjectMeta, T, S>;

/// Build an Orishu resource of the given kind.
///
/// Every caller is a resource module in this crate, which supplies its own
/// kind constant; this exists so the `orishu.dev/v1` version is written once.
pub(crate) fn resource<T, S>(kind: &'static str, name: &str, spec: T) -> Manifest<T, S> {
    Manifest::new(
        api_version(),
        Kind::from_static(kind),
        ObjectMeta::new(name),
        spec,
    )
}

/// Build an Orishu resource the owning system has already identified.
///
/// Separate from [`resource`] rather than an `Option` parameter, so a kind that
/// has no assigned identity to project cannot pass `None` and quietly grow one
/// later.
pub(crate) fn identified_resource<T, S>(
    kind: &'static str,
    name: &str,
    uid: ResourceUid,
    spec: T,
) -> Manifest<T, S> {
    Manifest::new(
        api_version(),
        Kind::from_static(kind),
        ObjectMeta::identified(name, uid),
        spec,
    )
}

/// Errors that can occur when parsing a `Manifest`.
#[derive(Debug)]
pub enum ParseError {
    /// The input is not well-formed JSON.
    Json(serde_json::Error),
    /// The input is not well-formed YAML.
    Yaml(serde_yaml::Error),
    /// Input bytes are not valid UTF-8.
    InvalidUtf8(std::str::Utf8Error),
    /// The document parsed successfully but is not the resource the caller
    /// asked for.
    ///
    /// The expected discriminator comes from the caller, so this reports the
    /// resource that was actually wanted rather than a hard-coded one.
    InvalidResource(UnexpectedDiscriminator),
    /// The resource decoded, but its spec fails domain validation.
    ///
    /// Owned here rather than by the shared envelope: what makes a workload
    /// domain inconsistent is Orishu's rule, and flattening it into a generic
    /// structural error would lose it.
    InvalidSpec {
        /// Human-readable description of the domain rule that was violated.
        details: String,
    },
}

impl From<UnexpectedDiscriminator> for ParseError {
    fn from(error: UnexpectedDiscriminator) -> Self {
        ParseError::InvalidResource(error)
    }
}

impl std::fmt::Display for ParseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ParseError::Json(e) => write!(f, "JSON parse error: {e}"),
            ParseError::Yaml(e) => write!(f, "YAML parse error: {e}"),
            ParseError::InvalidUtf8(e) => write!(f, "invalid UTF-8: {e}"),
            ParseError::InvalidResource(e) => e.fmt(f),
            ParseError::InvalidSpec { details } => write!(f, "invalid spec: {details}"),
        }
    }
}

impl std::error::Error for ParseError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            ParseError::Json(e) => Some(e),
            ParseError::Yaml(e) => Some(e),
            ParseError::InvalidUtf8(e) => Some(e),
            ParseError::InvalidResource(e) => Some(e),
            ParseError::InvalidSpec { .. } => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_orishu_api_version_constant_is_a_valid_discriminator() {
        // `api_version` panics on an invalid constant, so this is the test
        // that keeps that panic unreachable.
        assert_eq!(api_version().as_str(), MANIFEST_API_VERSION);
    }

    #[test]
    fn the_system_assigned_identifier_is_spelled_uid() {
        let metadata = ObjectMeta::identified("worker-a", ResourceUid("node-7f3a".to_owned()));
        assert_eq!(
            serde_json::to_string(&metadata).expect("metadata encodes"),
            r#"{"name":"worker-a","uid":"node-7f3a"}"#
        );
    }

    #[test]
    fn the_superseded_id_spelling_does_not_fill_uid() {
        // `ObjectMeta` tolerates unknown keys, so a document written against
        // the old spelling parses. It must not parse as an identified
        // resource: silently accepting `id` would leave two live spellings for
        // one field, which is exactly what making `uid` canonical settles.
        let metadata: ObjectMeta =
            serde_json::from_str(r#"{"name":"worker-a","id":"node-7f3a"}"#).expect("it decodes");
        assert!(metadata.uid.is_none());
    }

    #[test]
    fn a_mismatch_reports_the_resource_the_caller_asked_for() {
        let error = UnexpectedDiscriminator {
            expected_api_version: api_version(),
            expected_kind: Kind::from_static("Cluster"),
            found_api_version: api_version(),
            found_kind: Kind::from_static("Workload"),
        };
        assert_eq!(
            ParseError::InvalidResource(error).to_string(),
            r#"expected apiVersion="orishu.dev/v1" kind="Cluster", got apiVersion="orishu.dev/v1" kind="Workload""#
        );
    }
}
