use std::{collections::HashMap, str::FromStr};

use serde::{Deserialize, Serialize};

pub const MANIFEST_API_VERSION: &str = "orishu.dev/v1";

/// Manifested resource name.
///
/// See <https://kubernetes.io/docs/concepts/overview/working-with-objects/names/>.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Name(pub String);

impl std::fmt::Display for Name {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

impl std::str::FromStr for Name {
    type Err = std::convert::Infallible;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(Name(s.to_string()))
    }
}

/// Manifested resource ID generated by a system.
///
/// ID, unlike name is generated by a system and is expected to be unique within a namespace.
/// See <https://kubernetes.io/docs/concepts/overview/working-with-objects/names/>.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ID(pub String);

impl std::fmt::Display for ID {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

impl std::str::FromStr for ID {
    type Err = std::convert::Infallible;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(ID(s.to_string()))
    }
}

/// Descriptive metadata for identifying and organizing workloads.
/// Based on Kubernetes ObjectMeta:
/// <https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/>.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ObjectMeta {
    /// Human-readable name of the resource.
    pub name: Name,

    /// System generated resource name.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<ID>,

    /// Namespace defines the space within which each name must be unique.
    /// An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation.
    /// Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,

    /// Free-form key-value labels for filtering and grouping.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub labels: HashMap<String, String>,
}

impl ObjectMeta {
    fn new(name: &str) -> Result<Self, std::convert::Infallible> {
        Ok(Self {
            name: Name::from_str(name)?,
            id: None,
            namespace: None,
            labels: HashMap::default(),
        })
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Manifest<T, S> {
    /// Must be `"orishu.dev/v1"` for this version of the schema.
    pub api_version: String,
    /// Describes the type of the manifest and determines the type of Spec and Status field.
    /// This field is used to implement spec polymorphism.
    pub kind: String,

    /// Generic resource metadata, common to all resources
    pub metadata: ObjectMeta,

    /// Spec provides a description of the resource's desired state.
    pub spec: T,

    /// Runtime Status of the resource.
    /// It describes the current state of the object, usually estimated by the system.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<S>,
}

impl<T, S> Manifest<T, S> {
    pub fn new(name: &str, spec: T) -> Result<Self, std::convert::Infallible> {
        Ok(Self {
            api_version: MANIFEST_API_VERSION.into(),
            kind: "()".into(),
            metadata: ObjectMeta::new(name)?,
            spec,
            status: None,
        })
    }
}

/// Errors that can occur when parsing a `Manifest`.
#[derive(Debug)]
pub enum ParseError {
    Json(serde_json::Error),
    Yaml(serde_yaml::Error),
    /// Input bytes are not valid UTF-8.
    InvalidUtf8(std::str::Utf8Error),
    /// The document parsed successfully but `apiVersion` or `kind` are wrong.
    InvalidResource {
        api_version: String,
        kind: String,
    },
    InvalidSpec {
        details: String,
    },
}

impl std::fmt::Display for ParseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ParseError::Json(e) => write!(f, "JSON parse error: {e}"),
            ParseError::Yaml(e) => write!(f, "YAML parse error: {e}"),
            ParseError::InvalidUtf8(e) => write!(f, "invalid UTF-8: {e}"),
            ParseError::InvalidResource { api_version, kind } => {
                write!(
                    f,
                    "expected apiVersion=\"orishu.dev/v1\" kind=\"Workload\", \
                     got apiVersion=\"{api_version}\" kind=\"{kind}\""
                )
            }
            ParseError::InvalidSpec { details } => write!(f, "invalid spec: {details}"),
        }
    }
}

impl std::error::Error for ParseError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            ParseError::Json(e) => Some(e),
            ParseError::Yaml(e) => Some(e),
            ParseError::InvalidUtf8(e) => Some(e),
            ParseError::InvalidResource { .. } | ParseError::InvalidSpec { .. } => None,
        }
    }
}
