use std::str::FromStr;

use crate::model::{
    QuerySet,
    manifest::{self, Manifest as DefManifest},
    storage::StorageBackend,
};
use serde::{Deserialize, Serialize};

/// Node manifest kind
pub const NODE_MANIFEST_KIND: &str = "Node";

/// Stable, globally unique identity of a cluster node.
/// Node IDs are generated by the cluster at admission time and are not expected to be human-friendly.
/// They are opaque strings with no semantic meaning, and should be treated as unstructured identifiers.
/// They are not guaranteed to be sequential or compact, and may be UUIDs or similar formats.
pub type NodeId = manifest::ID;

/// Operational role flags read from the node's startup configuration.
/// Observed by peers via gossip protocol.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NodeAccepts {
    /// Whether the node accepts direct connections from operator/user clients.
    pub clients: bool,
    /// Whether the node accepts join requests from new peers (acts as introducer/seed).
    pub peers: bool,
    /// Whether the node accepts new workload partitions. When false the node is cordoned.
    pub work: bool,
}

/// Hardware resources advertised by a node.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NodeCapabilities {
    /// Number of CPU cores this node has access to
    pub cpu_cores: u32,
    /// Amount of memory available to this node
    pub memory_bytes: u64,
    /// e.g. "x86_64", "aarch64"
    pub architecture: String,
    /// Storage backend summary
    pub storage: NodeStorage,
    /// Accelerator descriptions (GPU model, OpenCL version, etc.).
    pub accelerators: Vec<String>,
}

/// Info about Node storage configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NodeStorage {
    /// Maximum number of peer connections this node will accept. `0` - no limit set.
    pub driver: StorageBackend,
    /// Number of additional node the data partition is replicated to. `1` - no copy.
    pub replicas: Option<u32>,
}

impl Default for NodeStorage {
    /// The default address is the local node's Unix domain socket.
    /// Matches the behavior of running `orishu-ctl` or `orishu-monitor` without `--host`.
    fn default() -> Self {
        Self {
            driver: StorageBackend::Memory,
            replicas: None,
        }
    }
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NodeLimits {
    /// Maximum number of peer connections this node will accept. `0` - no limit set.
    pub peers: Option<u32>,
    /// Maximum number of client connections this node will accept. `0` - no limit set.
    pub clients: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NodeListen {
    /// Hostname or IP advertised for for peer connections.
    pub peers: Vec<String>,
    /// Hostname or IP advertised for client connections. Empty if the node does not accept clients.
    pub clients: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NodeSpec {
    pub accepts: NodeAccepts,
    pub limits: NodeLimits,
    pub listen: NodeListen,
}

/// Hardware resources advertised by a node.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConnectionStats {
    /// Current number of peer connections
    pub peers: u32,

    /// Current number of active client connections
    pub clients: u32,
}

/// Controls where node manifest data is fetched from during `inspect`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum InspectSource {
    /// Fetch directly from the target node. Most up-to-date but requires the node to be reachable.
    Direct,
    /// Return from another node's gossip-based view, without contacting the target.
    Indirect,
    /// Try direct first, fall back to gossip-cached if unreachable (default).
    BestEffort,
}

impl std::fmt::Display for InspectSource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Direct => f.write_str("direct"),
            Self::Indirect => f.write_str("indirect"),
            Self::BestEffort => f.write_str("best-effort"),
        }
    }
}

/// Controls how a node is removed from the cluster.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum RemoveMode {
    /// Default. The node finishes in-flight work, transfers result data to
    /// replicas, and exits cleanly.
    Graceful,
    /// Drop the node immediately. Peers are instructed to reject any pending
    /// results or state transfers from it, preventing potentially corrupted
    /// data from entering the simulation.
    Force,
}

impl QuerySet for &RemoveMode {
    fn to_query(&self) -> String {
        match self {
            RemoveMode::Graceful => String::new(),
            RemoveMode::Force => String::from_str("force=true").unwrap(),
        }
    }
}

/// Result of a node connectivity and health diagnostic.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DiagnosticResult {
    pub target_id: NodeId,
    /// Node that performed the check. Same as target for a direct check.
    pub source_id: Option<NodeId>,
    pub reachable: bool,
    pub latency_ms: Option<u64>,
    pub details: Option<String>,
}

/// Lifecycle membership state of a node as seen by the cluster.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum MemberState {
    Alive,
    Suspected,
    Dead,
    Removed,
}

/// Node state describing current dynamic state
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NodeStatus {
    /// semver version of the running worker process.
    pub version: String,

    /// SHA-256 fingerprint of the node's mTLS certificate.
    pub cert_fingerprint: Vec<u8>,

    /// Runtime-only current stats number (not CRDT-replicated).
    pub connected: ConnectionStats,

    pub capabilities: NodeCapabilities,

    /// Cluster membership status
    /// Note, node is not expected to self report it.
    /// If you get a reply from the node itself, its alive.
    /// If you asked about node another peer, you can get different membership estimate.
    /// Such is nature of a swarm system.
    pub member: MemberState,
}

/// A single cluster member as known to the rest of the cluster.
pub type Manifest = DefManifest<NodeSpec, NodeStatus>;
